name = "GroupedTables"
uuid = "07903412-be78-4dbf-a59e-1531839e8cd4"
authors = ["Fabian Greimel <fabgrei@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
